services:
  - type: web
    name: edunexlms-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false